RevisionExam1_Equipe/Models/Client.cs
namespace RevisionExam1_Equipe.Models;

public class Client
{
    public int NumClient { get; set; }
    public string Nom { get; set; }
    public string Prenom { get; set; }

    public Client() { }

    public Client(int numClient, string nom, string prenom) 
    {
        NumClient = numClient;
        Nom = nom;
        Prenom = prenom;
    }
}

RevisionExam1_Equipe/Models/DB_Clients_ViewModel.cs
namespace RevisionExam1_Equipe.Models
{
    public class DB_Clients_ViewModel
    {
        public static List<Client> ListeClients = new List<Client>()
        {
            new Client(1, "Dupont", "Jean"),
            new Client(2, "Martin", "Marie"),
            new Client(3, "Dubé", "François"),
            new Client(4, "Trudeau", "Mélanie"),
            new Client(5, "Lambert", "Pierre")
        };
    }
}

RevisionExam1_Equipe/Models/DB_Livres_ViewModel.cs
namespace RevisionExam1_Equipe.Models;

public static class DB_Livres_ViewModel
{
    public static List<LivreModel> ListeLivres { get; set; } = new List<LivreModel>() 
    {
        new LivreModel(1, "Le Petit Prince", 10.99),
        new LivreModel(2, "1984", 8.99),
        new LivreModel(3, "Le Meilleur des Mondes", 12.50),
        new LivreModel(4, "Fahrenheit 451", 9.99),
        new LivreModel(5, "La liberté n'est pas une maqrue de yogourt", 30.99),
    };
}

RevisionExam1_Equipe/Models/ErrorViewModel.cs
namespace RevisionExam1_Equipe.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RevisionExam1_Equipe/Models/LivreModel.cs
namespace RevisionExam1_Equipe.Models;

public class LivreModel
{
    public int Id { get; set; }
    public string Titre { get; set; }
    public double Prix { get; set; }
    public LivreModel() 
    {
        Id = 0;
        Titre = "Non-disponible (Voir ID?)";
        Prix = 0.0;
    }
    public LivreModel(int id, string titre, double prix)
    {
        Id = id;
        Titre = titre;
        Prix = prix;
    }
}

RevisionExam1_Equipe/Models/ViewModel/Panier.cs
namespace RevisionExam1_Equipe.Models.ViewModel;

public class Panier
{
    public Client Client { get; set; }
    public List<LivreModel> ListePanier { get; set; }
}

RevisionExam1_Equipe/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RevisionExam1_Equipe.Models;

namespace RevisionExam1_Equipe.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RevisionExam1_Equipe/Controllers/InscriptionController.cs
using Microsoft.AspNetCore.Mvc;
using RevisionExam1_Equipe.Models;

namespace RevisionExam1_Equipe.Controllers
{
    public class InscriptionController : Controller
    {
        public IActionResult Index()
        {
            return View(DB_Clients_ViewModel.ListeClients);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Client client)
        {
            int id = client.NumClient;
            string nom = client.Nom;
            string prenom = client.Prenom;
            if (DB_Clients_ViewModel.ListeClients.Any(c => c.NumClient == id))
            {
                return Content($"Le client ayant le ID:{id} existe déjà!");
            }
            else
            {
                DB_Clients_ViewModel.ListeClients.Add(client);
                return RedirectToAction("Index");
            }
            
        }
        public IActionResult Edit() 
        {
            return View();
        }
        [HttpPost]
        public IActionResult Edit(Client client)
        {
            int id = client.NumClient;
            string nom = client.Nom;
            string prenom = client.Prenom;
            if (DB_Clients_ViewModel.ListeClients.Any(c => c.NumClient == id))
            {
                int index = DB_Clients_ViewModel.ListeClients.FindIndex(c => c.NumClient == id);
                DB_Clients_ViewModel.ListeClients[index]= client;
                return RedirectToAction("Index");
            }
            else
            {
                return Content($"Le client ayant le ID:{id} n'existe pas!");
            }
        }
        public IActionResult Delete(int id)
        {
            DB_Clients_ViewModel.ListeClients.RemoveAll(c => c.NumClient == id);
            return View(id);
        }
    }
}

RevisionExam1_Equipe/Controllers/LivreController.cs
using Microsoft.AspNetCore.Mvc;
using RevisionExam1_Equipe.Models;

namespace RevisionExam1_Equipe.Controllers
{
    public class LivreController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Catalogue()
        {
            return View(DB_Livres_ViewModel.ListeLivres);
        }
        public IActionResult TrouverLivre(int id)
        {
            LivreModel? livre = DB_Livres_ViewModel.ListeLivres.FirstOrDefault(l => l.Id == id);
            if (livre != null)
            {
                return View(livre);
            }
            else
            {
                return Content($"Le livre ayant le ID:{id} n'est pas disponible!");
            }
        }
    }
}

RevisionExam1_Equipe/Controllers/PanierController.cs
using Microsoft.AspNetCore.Mvc;
using RevisionExam1_Equipe.Models;
using RevisionExam1_Equipe.Models.ViewModel;

namespace RevisionExam1_Equipe.Controllers
{
    public class PanierController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Panier(int idClient, int? idLivre1, int? idLivre2, int? idLivre3)
        {
            // Récupérer le client
            Client? client = DB_Clients_ViewModel.ListeClients.FirstOrDefault(c => c.NumClient == idClient);
            LivreModel livre1 = new();
            LivreModel livre2 = new();
            LivreModel livre3 = new();
            // Récupérer les livres


            if (client != null) 
            {
                // Créer le panier
                Panier panier = new ();
                panier.Client = client;
                panier.ListePanier = new List<LivreModel>();

                // Ajouter les livres au panier, pourrait être optimisé dans un loop
                if (idLivre1 != null && DB_Livres_ViewModel.ListeLivres.FirstOrDefault(l => l.Id == idLivre1) != null)
                {
                    livre1 = DB_Livres_ViewModel.ListeLivres.FirstOrDefault(l => l.Id == idLivre1);
                    panier.ListePanier.Add(livre1);
                }

                if (idLivre2 != null && DB_Livres_ViewModel.ListeLivres.FirstOrDefault(l => l.Id == idLivre2) != null)
                {
                    livre2 = DB_Livres_ViewModel.ListeLivres.FirstOrDefault(l => l.Id == idLivre2);
                    panier.ListePanier.Add(livre2);
                }

                if (idLivre3 != null && DB_Livres_ViewModel.ListeLivres.FirstOrDefault(l => l.Id == idLivre3) != null)
                {
                    livre3 = DB_Livres_ViewModel.ListeLivres.FirstOrDefault(l => l.Id == idLivre3);
                    panier.ListePanier.Add(livre3);
                }
                // Passer le panier à la vue
                return View(panier);
            }
            else
            {
                return Content($"Le client ayant le ID:{idClient} n'est pas disponible!");
            }
        }
    }
}

RevisionExam1_Equipe/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RevisionExam1_Equipe/Views/Inscription/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	ViewBag.Title = "Créer une Inscription";
}
@model RevisionExam1_Equipe.Models.Client
<h1>Créer une inscription</h1>
@using (Html.BeginForm("Create", "Inscription", FormMethod.Post))
{
    <table cellpadding="0" cellspacing="0">
        <tr>
            <th colspan="2" align="center">Person Details</th>
        </tr>
        <tr>
            <td>PersonId: </td>
            <td>
                @Html.TextBoxFor(m => m.NumClient)
            </td>
        </tr>
        <tr>
            <td>Nom: </td>
            <td>
                @Html.TextBoxFor(m => m.Nom)
            </td>
        </tr>

        <tr>
            <td>Prénom: </td>
            <td>
                @Html.TextBoxFor(m => m.Prenom)
            </td>
        </tr>

        <tr>
            <td></td>
            <td><input type="submit" value="Submit" /></td>
        </tr>
    </table>
}
<a href="@Url.Action("Index", "Inscription")" class="btn btn-primary">Retour à la liste des Inscriptions</a>

RevisionExam1_Equipe/Views/Inscription/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Supprimer client</h1>
<p>
	Le client avec le id: @Model a été supprimé avec succès.
</p>
<a href="@Url.Action("Index", "Inscription")">Retour à la liste</a>

RevisionExam1_Equipe/Views/Inscription/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model RevisionExam1_Equipe.Models.Client
<h1>Modifier client</h1>
@using (Html.BeginForm("Edit", "Inscription", FormMethod.Post))
{
    <table cellpadding="0" cellspacing="0">
        <tr>
            <th colspan="2" align="center">Person Details</th>
        </tr>
        <tr>
            <td>PersonId: </td>
            <td>
                @Html.TextBoxFor(m => m.NumClient)
            </td>
        </tr>
        <tr>
            <td>Nom: </td>
            <td>
                @Html.TextBoxFor(m => m.Nom)
            </td>
        </tr>

        <tr>
            <td>Prénom: </td>
            <td>
                @Html.TextBoxFor(m => m.Prenom)
            </td>
        </tr>

        <tr>
            <td></td>
            <td><input type="submit" value="Submit" /></td>
        </tr>
    </table>
}
<a href="@Url.Action("Index", "Inscription")">Retour à la liste</a>

RevisionExam1_Equipe/Views/Inscription/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	ViewBag.Title = "Inscriptions";
}
<h1>Inscriptions</h1>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2>Liste des Inscriptions</h2>
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>Nom</th>
						<th>Prénom</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var inscription in Model)
					{
						<tr>
							<td>@inscription.Nom</td>
							<td>@inscription.Prenom</td>
							<td>
								<a href="@Url.Action("Edit", "Inscription", new { id = inscription.NumClient })" class="btn btn-primary">Modifier</a>
								<a href="@Url.Action("Delete", "Inscription", new { id = inscription.NumClient })" class="btn btn-danger">Supprimer</a>
							</td>
						</tr>
					}
				</tbody>
			</table>
			<a href="@Url.Action("Create", "Inscription")" class="btn btn-success">Ajouter une Inscription</a>
			@if (TempData["Message"] != null)
			{
				<div class="alert alert-success">
					@TempData["Message"]
				</div>
			}

			@if (TempData["Error"] != null)
			{
			<div class="alert alert-danger">
				@TempData["Error"]
			</div>
			}
		</div>
	</div>
</div>

RevisionExam1_Equipe/Views/Livre/Catalogue.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using RevisionExam1_Equipe.Models;
@{
    ViewData["Title"] = "Catalogue";
}
<h1>Catalogue</h1>
<ol>
    @foreach (LivreModel livre in Model)
    {
        <li>
            <a asp-action="TrouverLivre" asp-controller="Livre" asp-route-id="@livre.Id">
                @livre.Titre, @livre.Prix $
            </a>
        </li>
    }
</ol>

RevisionExam1_Equipe/Views/Livre/Panier.cshtml
@using RevisionExam1_Equipe.Models
@using RevisionExam1_Equipe.Models.ViewModel

@model Panier

<h1>Panier</h1>

<h2>Bienvenue @Model.Client.Prenom @Model.Client.Nom !</h2>
<p>Numéro Client : @Model.Client.NumClient</p>

<h2>Contenu du panier</h2>

<table class="table">
	<tr>
		<th>ID</th>
		<th>Titre du Livre</th>
		<th>Prix</th>
	</tr>
	@foreach (var item in Model.ListePanier)
	{
		<tr>
			<td>@item.Id</td>
			<td>@item.Titre</td>
			<td>@item.Prix</td>
		</tr>
	}
</table>

RevisionExam1_Equipe/Views/Livre/TrouverLivre.cshtml
@using RevisionExam1_Equipe.Models;
@model RevisionExam1_Equipe.Models.LivreModel
@{
    ViewData["Title"] = "TrouverLivre";
}
<h1>@Model.Titre</h1>
<p>
    <strong>Prix:</strong> @Model.Prix $<br />
    <strong>Id:</strong> @Model.Id<br />

</p>
<a href="@Url.Action("Catalogue", "Livre")">Retour au catalogue</a>

RevisionExam1_Equipe/Views/Panier/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Waaaaaaaza index du panier</h1>

RevisionExam1_Equipe/Views/Panier/Panier.cshtml
@using RevisionExam1_Equipe.Models
@using RevisionExam1_Equipe.Models.ViewModel

@model Panier

<h1>Panier</h1>

<h2>Bienvenue @Model.Client.Prenom @Model.Client.Nom !</h2>
<p>Numéro Client : @Model.Client.NumClient</p>

<h2>Contenu du panier</h2>

<table class="table">
	<tr>
		<th>ID</th>
		<th>Titre du Livre</th>
		<th>Prix</th>
	</tr>
	@foreach (var item in Model.ListePanier)
	{
		<tr>
			<td>@item.Id</td>
			<td>@item.Titre</td>
			<td>@item.Prix</td>
		</tr>
	}
</table>
<p>Total : @Model.ListePanier.Sum(li => li.Prix) $</p>

RevisionExam1_Equipe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RevisionExam1_Equipe</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RevisionExam1_Equipe.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RevisionExam1_Equipe</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - RevisionExam1_Equipe - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>